name: Build & Deploy

on:
  workflow_dispatch

jobs:
  build-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12.10.0'
      - run: sudo apt-get install sshpass
      - run: npm install -g @angular/cli
      - run: npm --version
      - run: ng --version
      - run: npm i -f

      - name: Minimify json assets
        run: python3 minimify_assets.py

      - name: Build prod
        run: ng build --prod

      - name: Check Hash
        run: npm run post-build

      - name: Install Sentry-cli
        run: curl -sL https://sentry.io/get-cli/ | bash

      - name: Copy sentry config
        run: cp .github/files/.sentryclirc ~/.sentryclirc

      - name: Sentry Release
        run: sentry-cli releases --org wotv-calc --project wotv-calc files prod upload-sourcemaps dist/browser --rewrite

      - name: Remove sourcemaps
        run : rm dist/browser/*.map

      - name: Compress build
        run : tar -czvf build.tar.gz ./dist

      - name: Copy New Files to server
        run : sudo sshpass -p ${{ secrets.SSH_PASS }} scp -v -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} -r build.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}:${{ secrets.SSH_TARGET }}

      - name: Delete Existing Files
        run : sudo sshpass -p ${{ secrets.SSH_PASS }} -v ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT}} ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }} 'rm -rf ${{ secrets.SSH_TARGET }}/dist/*'
        continue-on-error: true

      - name: Uncompress new Files
        run : sudo sshpass -p ${{ secrets.SSH_PASS }} -v ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT}} ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }} 'cd ${{ secrets.SSH_TARGET }} && tar -xzvf build.tar.gz && rm build.tar.gz'

