name: Build & Deploy Beta

on:
  workflow_dispatch

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.10.0'
      - run: npm install -g @angular/cli
      - run: ng --version
      - run: npm install
        
