name: Build & Deploy

on:
  workflow_dispatch

jobs:
  build-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.14.0'
      - run: sudo apt-get install sshpass libsqlite3-dev
      - run: npm cache clean --force
      - run: npm install -g @angular/cli
      - run: npm --version
      - run: ng version
      - run: npm i -f

      - name: Minimify json assets
        run: python3 minimify_assets.py

      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v5.3.0
          with:
            gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
            passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}

      - name: Git Secret Reveal
        run: git secret reveal

      - run: ng version

      - name: Build prod
        run: npm run build:ssr

      - name: Remove sourcemaps
        run : rm dist/wotv-calc/browser/*.map

      - name: Compress build
        run : tar -czvf build.tar.gz ./dist ./.pm2 ./.keys

      - name: Copy New Files to server
        run : sudo sshpass -p ${{ secrets.SSH_PASS }} scp -v -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} -r build.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}:${{ secrets.SSH_TARGET }}

      - name: Delete Existing Files
        run : sudo sshpass -p ${{ secrets.SSH_PASS }} -v ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT}} ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }} 'rm -rf ${{ secrets.SSH_TARGET }}/dist/* ${{ secrets.SSH_TARGET }}/.pm2/* ${{ secrets.SSH_TARGET }}/.keys/*'
        continue-on-error: true

      - name: Uncompress new Files
        run : sudo sshpass -p ${{ secrets.SSH_PASS }} -v ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT}} ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }} 'cd ${{ secrets.SSH_TARGET }} && tar -xzvf build.tar.gz && rm build.tar.gz'

      - name: Reload back process
        run : sudo sshpass -p ${{ secrets.SSH_PASS }} -v ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT}} ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }} 'pm2 reload all'
