name: Quality

on:
  push

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12.10.0'
      - run: npm install -g @angular/cli
      - run: npm --version
      - run: ng --version
      - run: npm i -f
        
      - name: Lint
        run: ng lint
